sonar.projectKey=addressbook
sonar.projectName=Address Book Application
sonar.projectVersion=1.0

sonar.sources=.
sonar.java.binaries=bin
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin


